pypi-dwh:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: "pypi-dwh"
      dataset: "numfocus_pypi"
      threads: 10
      timeout_seconds: 300
      location: US
      priority: interactive
