name: dbt-run

on:
  push:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: your-gcp-project-id
  DBT_GOOGLE_BIGQUERY_DATASET: bigquery-dataset-id
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.11"

      - run: pip install -r requirements.txt

      - run: dbt --version

      - name: Set up Google Cloud credentials
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

      - run: dbt run

      - run: dbt test
